name: Main CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: echo "$E" > .env
        env:
          E: ${{ secrets.ENV }}

      - run: npm ci
      - name: build
        run: |
          npm run build
