# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: PR Build CI

on:
  pull_request:
    branches: [main]
  pull_request_target:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    # If the PR is coming from a fork (pull_request_target), ensure it's opened by "dependabot[bot]".
    # Otherwise, clone it normally.
    if: |
        (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
        (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')
    steps:

      - name: Checkout
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v2
      
      - name: Checkout PR
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: echo "$E" > .env
        env:
          E: ${{ secrets.ENV }}

      - run: npm ci
      - name: build
        run: |
          npm run build
