# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.4.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: echo $E > .env
      env:
        E: ${{ secrets.ENV }}

    - run: npm ci
    - run: npm run build

    - name: push
      run: |
        token=(`grep TOKEN .env | cut -f 2 -d=`)
        username=(`grep username: config.ts | cut -f2 -d\'`)
        repo=(`grep base config.ts | cut -f2 -d\'`)
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        cd dist
        git init
        git add .
        git commit -m deploy
        echo "git push --force https://$username:$token@github.com/$username/$repo.git master:gh-pages"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
